# Generated by Django 3.2.9 on 2021-11-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ramo', models.CharField(max_length=8)),
                ('archvio', models.FileField(blank=True, null=True, upload_to='myfolder/')),
            ],
        ),
    ]
