# Generated by Django 3.2.9 on 2021-11-14 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblio', '0004_post_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='titulo',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
