# Generated by Django 3.2.9 on 2021-12-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblio', '0008_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='likes',
            field=models.ManyToManyField(related_name='UserPost', to='Biblio.Post'),
        ),
    ]
